# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17inventory_service.proto\x12\x08ordermgt\"\x1b\n\x0bProductType\x12\x0c\n\x04type\x18\x01 \x01(\t\"*\n\x08Quantity\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\x12\x0e\n\x06metric\x18\x02 \x01(\t\"\x9a\x01\n\x0cStockSummary\x12@\n\rproductStocks\x18\x01 \x03(\x0b\x32).ordermgt.StockSummary.ProductStocksEntry\x1aH\n\x12ProductStocksEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.ordermgt.Quantity:\x02\x38\x01\x32\x9b\x01\n\x10InventoryService\x12\x41\n\x12GetProductQuantity\x12\x15.ordermgt.ProductType\x1a\x12.ordermgt.Quantity\"\x00\x12\x44\n\x0fGetStockSummary\x12\x15.ordermgt.ProductType\x1a\x16.ordermgt.StockSummary\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STOCKSUMMARY_PRODUCTSTOCKSENTRY']._options = None
  _globals['_STOCKSUMMARY_PRODUCTSTOCKSENTRY']._serialized_options = b'8\001'
  _globals['_PRODUCTTYPE']._serialized_start=37
  _globals['_PRODUCTTYPE']._serialized_end=64
  _globals['_QUANTITY']._serialized_start=66
  _globals['_QUANTITY']._serialized_end=108
  _globals['_STOCKSUMMARY']._serialized_start=111
  _globals['_STOCKSUMMARY']._serialized_end=265
  _globals['_STOCKSUMMARY_PRODUCTSTOCKSENTRY']._serialized_start=193
  _globals['_STOCKSUMMARY_PRODUCTSTOCKSENTRY']._serialized_end=265
  _globals['_INVENTORYSERVICE']._serialized_start=268
  _globals['_INVENTORYSERVICE']._serialized_end=423
# @@protoc_insertion_point(module_scope)
