apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: training-api
  name: training-api
  namespace: myapps
spec:
  replicas: 2 # Creating two replicas of the POD
  selector:
    matchLabels:
      app: training-api
  template:
    metadata:
      labels:
        app: training-api
    spec:
      containers:
      - image: LOCATION-docker.pkg.dev/PROJECT_ID/labrepo/training-api:0.0.1 # Docker image name, that we pushed to GCR - use your project id, location, and repository
        name: training-api
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: PROJECT_ID
          value: vertical-theory-413015 # use your project id
        - name: MODEL_REPO
          value: labrepo # use your GCP bucket id
        - name: MODEL_NAME
          value: model.h5