apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-gce-pd-provisioning
  labels:
    demo: nfs-pv-provisioning
  namespace: mynfs
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 50Gi