apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-model-repo
  namespace: diabetes-fs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: nfs