apiVersion: v1
kind: Service
metadata:
  name: prediction-api-fs-service
  namespace: diabetes-fs
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 5000
  selector:
    app: prediction-api-fs