apiVersion: v1
kind: Service
metadata:
  name: training-api-fs-service
  namespace: diabetes-fs
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: training-api-fs